[tools]
node = "latest"
pnpm = "latest"
python = "latest"
usage = "latest"
uv = "latest"
# rust
rust = { version = "latest", profile = "default", components = "rust-analyzer,rust-src" }
cargo-binstall = "latest"
# typst tooling
typst = "latest"
typstyle = "latest"
websocat = "latest"
# task runner
"cargo:bacon" = "latest"
# iso burner
"cargo:caligula" = "latest"
"cargo:leetcode-cli" = "latest"
# loc counter
tokei = "latest"
# cli file manager
yazi = "latest"
# check broken links
lychee = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
